version: '3.7'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
      target: "ruber-local"
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules/
    depends_on:
      - redis 
  redis:
    container_name: cache
    image: "redis:alpine"
