 version: 2
 jobs:
   build:
     docker:
       - image: rmferrer/uber-via-text:test-v1
         environment:
           UBER_COOKIES: $UBER_COOKIES
     working_directory: ~/repo
     steps:
       - checkout
       - run: npm install
       - run: bash scripts/display.sh & npm test
